spring:
  application:
    name: twitter-clone-admin
  datasource:
    url: jdbc:mariadb://localhost:3306/twitter_clone_db_dev
    username: wassup
    password: wassup
    hikari:
      maximum-pool-size: 30

server:
  port: 8081