spring:
  application:
    name: twitter-clone-admin
  datasource:
    url: jdbc:mariadb://localhost:3306/twitter_clone_db_dev
    username: wassup
    password: wassup
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  thymeleaf:
    cache: false
server:
  port: 8081
  servlet:
    session:
      timeout: 1800
